<?php
/**
 * BENCH-D7 regression test — thundering herd / stampede protection.
 *
 * HARDEN-1: Verifies that the GenerationLock + Engine::intercept() single-flight
 * logic prevents N concurrent MISSes from spawning N PHP renders.
 *
 * @package UltimatePerformance\Tests
 */

namespace UltimatePerformance\Tests;

if ( PHP_SAPI !== 'cli' ) {
        exit( 1 );
}

define( 'ABSPATH', __DIR__ . '/wp-shim/' ); // portable WP shim.
define( 'WP_CONTENT_DIR', ABSPATH . 'wp-content' );
define( 'ULTIMATE_PERFORMANCE_TESTING', true );
define( 'ULTIMATE_PERFORMANCE_DIR', str_replace( '\\', '/', __DIR__ ) . '/../' );
define( 'DOING_CRON', false ); // phpcs:ignore -- allow full WP shim boot

require_once ULTIMATE_PERFORMANCE_DIR . 'vendor/autoload.php';
require_once ULTIMATE_PERFORMANCE_DIR . 'src/Core/Autoloader.php';
\UltimatePerformance\Core\Autoloader::register();
require ABSPATH . 'wp-load.php';

use UltimatePerformance\Core\Installer;
use UltimatePerformance\Core\SafeFs;
use UltimatePerformance\PageCache\GenerationLock;
use UltimatePerformance\PageCache\Store;
use UltimatePerformance\CacheKey\Key;
use UltimatePerformance\Core\Settings;

echo "=== BENCH-D7 Herd Regression Test ===\n";

// Setup: ensure cache root + genlocks dir.
Installer::ensure_cache_root();
GenerationLock::ensure_dir();

// Clean state.
$sfs = new SafeFs();
$cache_root = Installer::cache_root();
$genlocks_dir = $cache_root . '/genlocks';
// Clear any existing genlocks.
if ( is_dir( $genlocks_dir ) ) {
        foreach ( glob( $genlocks_dir . '/*.lock' ) as $f ) {
                @unlink( $f );
        }
}
// Clear the target cache entry.
$sfs->delete_tree( $cache_root . '/v' );
Installer::ensure_cache_root();
GenerationLock::ensure_dir();

// Test key.
$rel_dir = 'herd-test.example.com/edge-case-page';
$keygen = new Key( Settings::instance() );

$test_file = $keygen->absolute( $rel_dir );
echo "Test cache file: $test_file\n";

// ============================================================
// Test 1: GenerationLock basic acquire/release semantics
// ============================================================
echo "\n--- Test 1: GenerationLock basic acquire/release ---\n";
GenerationLock::ensure_dir();
$lock1 = new GenerationLock( $rel_dir );
$lock2 = new GenerationLock( $rel_dir );

$got1 = $lock1->try_acquire( 30 );
$got2 = $lock2->try_acquire( 30 );
echo "lock1 acquire: " . ( $got1 ? 'YES (generator)' : 'NO' ) . "\n";
echo "lock2 acquire: " . ( $got2 ? 'YES (BUG — should be NO)' : 'NO (waiter, correct)' ) . "\n";

if ( $got1 && ! $got2 ) {
        echo "[PASS] Single-flight: only one acquirer wins\n";
} else {
        echo "[FAIL] Single-flight broken: got1=" . var_export( $got1, true ) . " got2=" . var_export( $got2, true ) . "\n";
}

$lock1->release();
echo "[PASS] Lock release succeeded\n";

// After release, lock2 should now be able to acquire.
$got2b = $lock2->try_acquire( 30 );
if ( $got2b ) {
        echo "[PASS] Lock2 acquired after lock1 release\n";
        $lock2->release();
} else {
        echo "[FAIL] Lock2 could NOT acquire after release (deadlock)\n";
}

// ============================================================
// Test 2: Concurrent fork — c100 cold-cache burst
// ============================================================
echo "\n--- Test 2: Concurrent fork (c20 cold-cache burst) ---\n";
echo "Simulating 20 concurrent requests hitting a cold cache.\n";
echo "Expected: ~1 generator, others wait and serve fresh cache.\n";

// Clear state.
$sfs->delete_tree( $cache_root . '/v' );
Installer::ensure_cache_root();
GenerationLock::ensure_dir();
foreach ( glob( $genlocks_dir . '/*.lock' ) as $f ) {
        @unlink( $f );
}

$children = array();
$child_count = 20;
$pipe_path = tempnam( sys_get_temp_dir(), 'ucherd_' );
@unlink( $pipe_path );

for ( $i = 0; $i < $child_count; $i++ ) {
        $pid = pcntl_fork();
        if ( -1 === $pid ) {
                echo "[FAIL] fork failed at $i\n";
                break;
        } elseif ( 0 === $pid ) {
                // Child process.
                $child_id = $i;
                $role = 'unknown';

                Installer::ensure_cache_root();
                GenerationLock::ensure_dir();

                $lock = new GenerationLock( $rel_dir );
                $is_generator = $lock->try_acquire( 30 );

                if ( $is_generator ) {
                        $role = 'generator';
                        // Simulate expensive render (~100ms).
                        usleep( 100000 );
                        // Write the cache file.
                        $body = '<!DOCTYPE html><html><body><h1>Herd Test Page</h1><p>Generated by child ' . $child_id . '</p><p>Padding ' . str_repeat( 'x', 200 ) . '</p></body></html>';
                        $fs = new SafeFs();
                        $store = new Store( $fs, $keygen );
                        $store->write( $rel_dir, $body, 200, array( 'Content-Type' => 'text/html; charset=UTF-8' ), array(), 3600 );
                        $lock->release();
                } else {
                        $role = 'waiter';
                        // Poll for cache.
                        $store = new Store( new SafeFs(), $keygen );
                        $elapsed = 0;
                        $served = false;
                        while ( $elapsed < 2000000 ) { // 2s budget
                                usleep( 20000 + mt_rand( 0, 15000 ) );
                                $elapsed += 35000;
                                $lookup = $store->lookup( $rel_dir );
                                if ( is_array( $lookup ) && $lookup['found'] && $lookup['fresh'] ) {
                                        $served = true;
                                        break;
                                }
                        }
                        $role = $served ? 'waiter_served' : 'waiter_timeout';
                }

                // Write result to a per-child file.
                $result_file = $pipe_path . '_' . $child_id;
                file_put_contents( $result_file, $role );
                posix_kill( getmypid(), SIGKILL ); // ensure child exits
        } else {
                $children[] = $pid;
        }
}

// Parent: wait for all children.
foreach ( $children as $pid ) {
        pcntl_waitpid( $pid, $status );
}

// Collect results.
$generators = 0;
$waiters_served = 0;
$waiters_timeout = 0;
for ( $i = 0; $i < $child_count; $i++ ) {
        $result_file = $pipe_path . '_' . $i;
        if ( file_exists( $result_file ) ) {
                $role = trim( file_get_contents( $result_file ) );
                if ( 'generator' === $role ) {
                        $generators++;
                } elseif ( 'waiter_served' === $role ) {
                        $waiters_served++;
                } elseif ( 'waiter_timeout' === $role ) {
                        $waiters_timeout++;
                }
                @unlink( $result_file );
        }
}

// Verify cache file was produced.
$cache_file = $keygen->absolute( $rel_dir );
$cache_exists = file_exists( $cache_file );
$cache_size = $cache_exists ? filesize( $cache_file ) : 0;
$cache_valid = $cache_exists && $cache_size > 64 && false !== strpos( (string) file_get_contents( $cache_file ), 'Herd Test Page' );

echo "Generator count: $generators (expected: 1)\n";
echo "Waiters served: $waiters_served (expected: ~" . ( $child_count - 1 ) . ")\n";
echo "Waiters timeout: $waiters_timeout (expected: 0 or near-0)\n";
echo "Cache file exists: " . ( $cache_exists ? 'YES' : 'NO' ) . "\n";
echo "Cache file size: $cache_size bytes\n";
echo "Cache file valid: " . ( $cache_valid ? 'YES' : 'NO' ) . "\n";

// Acceptance criteria.
$pass = true;
if ( $generators > 3 ) {
        echo "[FAIL] Generator count $generators exceeds bound of 3 (stampede not prevented)\n";
        $pass = false;
} else {
        echo "[PASS] Generator count $generators is tightly bounded\n";
}
if ( ! $cache_exists ) {
        echo "[FAIL] No cache artifact produced\n";
        $pass = false;
} elseif ( ! $cache_valid ) {
        echo "[FAIL] Cache artifact corrupted or invalid\n";
        $pass = false;
} else {
        echo "[PASS] Cache artifact produced and valid\n";
}

// ============================================================
// Test 3: Lock file is NOT orphaned after release (no deadlock)
// ============================================================
echo "\n--- Test 3: No orphaned lock (deadlock check) ---\n";
// After the burst, a NEW request should be able to acquire immediately.
$lock_after = new GenerationLock( $rel_dir );
$got_after = $lock_after->try_acquire( 5 );
if ( $got_after ) {
        echo "[PASS] Post-burst lock acquisition succeeds (no deadlock)\n";
        $lock_after->release();
} else {
        echo "[FAIL] Post-burst lock acquisition FAILED (orphaned lock → deadlock)\n";
        $pass = false;
}

// Cleanup.
$sfs->delete_tree( $cache_root . '/v' );
foreach ( glob( $genlocks_dir . '/*.lock' ) as $f ) {
        @unlink( $f );
}

echo "\n=== SUMMARY ===\n";
echo $pass ? "[PASS] BENCH-D7 herd regression — all checks passed\n" : "[FAIL] BENCH-D7 herd regression — some checks failed\n";
exit( $pass ? 0 : 1 );
