<?php
/**
 * advanced-cache.php drop-in generator — PHP fallback serving path.
 *
 * HARDEN-5: When the web server cannot be configured for zero-PHP static
 * serving (shared hosting, no root), this drop-in provides a PHP-level
 * cache HIT path. It loads BEFORE WordPress fully boots, checks the cache,
 * and serves the cached response with minimal PHP overhead.
 *
 * Safety contract:
 *   - NEVER overwrites another plugin's advanced-cache.php
 *   - Detects ownership via a version marker comment
 *   - Safe activation/deactivation (installs on plugin activation if no
 *     conflict; removes on deactivation only if WE own it)
 *
 * @package UltimatePerformance
 */

namespace UltimatePerformance\Compatibility;

use UltimatePerformance\Core\Installer;
use UltimatePerformance\Core\Settings;

defined( 'ABSPATH' ) || exit;

final class AdvancedCacheDropin {

        /** Version marker embedded in the drop-in for ownership detection. */
        const OWNERSHIP_MARKER = '/* Ultimate Performance advanced-cache.php v1 */';

        /** @var string Drop-in path (wp-content/advanced-cache.php). */
        private $path;

        public function __construct() {
                $this->path = WP_CONTENT_DIR . '/advanced-cache.php';
        }

        /**
         * Check whether the drop-in is owned by Ultimate Performance.
         *
         * @return bool True if the file exists and contains our ownership marker.
         */
        public function is_owned_by_us() {
                if ( ! file_exists( $this->path ) || ! is_readable( $this->path ) ) {
                        return false;
                }
                $head = (string) file_get_contents( $this->path, false, null, 0, 256 );
                return false !== strpos( $head, self::OWNERSHIP_MARKER );
        }

        /**
         * Check whether the drop-in exists but is owned by another plugin.
         *
         * @return bool True if a foreign drop-in exists.
         */
        public function is_foreign() {
                if ( ! file_exists( $this->path ) ) {
                        return false;
                }
                return ! $this->is_owned_by_us();
        }

        /**
         * Install the drop-in if safe (no foreign drop-in present).
         *
         * @return bool True on success, false on conflict or write failure.
         */
        public function install() {
                if ( $this->is_foreign() ) {
                        return false; // Never overwrite another plugin's drop-in.
                }
                $code = $this->generate_code();
                if ( '' === $code ) {
                        return false;
                }
                // Atomic write via temp file + rename.
                $tmp = $this->path . '.tmp-' . substr( md5( uniqid( '', true ) ), 0, 8 );
                if ( false === file_put_contents( $tmp, $code ) ) {
                        return false;
                }
                if ( ! @rename( $tmp, $this->path ) ) {
                        @unlink( $tmp );
                        return false;
                }
                @chmod( $this->path, 0644 );
                return true;
        }

        /**
         * Remove the drop-in if owned by us.
         *
         * @return bool True on success.
         */
        public function remove() {
                if ( ! $this->is_owned_by_us() ) {
                        return false; // Only remove our own.
                }
                return @unlink( $this->path );
        }

        /**
         * Generate the drop-in PHP code.
         *
         * The generated code bootstraps just enough of WordPress to:
         *   1. Load the plugin's Autoloader + Settings
         *   2. Classify the request (bypass POST, logged-in, cart, etc.)
         *   3. Look up the cache for the current URL
         *   4. If fresh HIT: serve the cached body + exit (minimal PHP)
         *   5. If MISS: return, letting WordPress boot normally (Engine captures)
         *
         * @return string PHP code, or '' on failure.
         */
        private function generate_code() {
                $plugin_dir = ULTIMATE_PERFORMANCE_DIR;
                if ( ! is_dir( $plugin_dir ) ) {
                        return '';
                }

                // The drop-in runs BEFORE wp-settings.php, so ABSPATH is defined but
                // most WP functions are NOT available yet. We must define WP_CONTENT_DIR
                // fallback and load the autoloader directly.
                // CRITICAL: must start with <?php or PHP treats it as plain text.
                $code  = "<?php\n";
                $code .= self::OWNERSHIP_MARKER . "\n";
                $code .= "/* Generated by Ultimate Performance. Do not edit — regenerate via plugin. */\n";
                $code .= "if ( ! defined( 'ABSPATH' ) ) { exit; }\n";
                $code .= "if ( ! defined( 'WP_CONTENT_DIR' ) ) { define( 'WP_CONTENT_DIR', ABSPATH . 'wp-content' ); }\n";
                $code .= "if ( ! defined( 'ULTIMATE_PERFORMANCE_DIR' ) ) { define( 'ULTIMATE_PERFORMANCE_DIR', " . var_export( $plugin_dir, true ) . " ); }\n";
                $code .= "\n";
                // CRITICAL: Do NOT define WP function shims (wp_normalize_path, wp_parse_url,
                // trailingslashit, etc.) because they will conflict with the real WP versions
                // when wp-includes/*.php loads later. Instead, the FallbackServer must use
                // only PHP built-in functions OR the plugin's own classes (which are namespaced
                // and don't conflict). The FallbackServer::serve() method is designed to work
                // without any WP functions — it uses only PHP builtins + plugin classes.
                // Load autoloader + serve.
                $code .= "require_once ULTIMATE_PERFORMANCE_DIR . 'src/Core/Autoloader.php';\n";
                $code .= "\\UltimatePerformance\\Core\\Autoloader::register();\n";
                $code .= "\\UltimatePerformance\\Compatibility\\FallbackServer::serve();\n";

                return $code;
        }
}
